project:
  type: website
  output-dir: docs

website:
  favicon: bilder/favicon-32x32.png
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: ""
    anonymize-ip: true

  navbar:
    background: "transparent"
    foreground: "#5b8b6e"
    right:
      - href: index.qmd
        text: Home
      - href: vita.qmd
        text: Vita
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Data Science Projects
      - href: contact.qmd
        text: Contact
  page-footer: 
    background: "transparent"
    foreground: "#a3b9a4"
    left:  "&copy; 2024 Patrick Zerrer. Alle Rechte vorbehalten."
    right: 
      - icon: linkedin
        href: https://linkedin.com/in/patrick-zerrer-205b422a7
      - icon: github
        href: https://github.com/patrickzerrer
  
format:
  html:
    #theme: mint
    css: styles.css
    toc: false
    include-in-header: gtm_code_head.html
    #include-before-body: gtm_code_body.html



