project:
  type: website
  output-dir: docs

website:
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: ""
    anonymize-ip: true

  navbar:
    background: "transparent"
    foreground: "#ffff"
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: Vita
      - href: research.qmd
        text: Research
      - href: data_science_projects.qmd
        text: Data Science Projects
      - href: about.qmd
        text: Contact
  page-footer: 
    background: "transparent"
    foreground: "white"
    left: "Copyright 2024" 
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/patrick-zerrer-205b422a7
  
format:
  html:
    #theme: mint
    css: styles.css
    toc: false
    include-in-header: gtm_code_head.html
    #include-before-body: gtm_code_body.html



