---
format: html
page-layout: full
---

<style>
  body {
    margin: 0;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #4a6e4f; /* Hintergrundfarbe */
    font-family: Georgia, sans-serif;
    flex-direction: column; /* Erlaubt vertikales Anordnen der Elemente */
  }

  .center-text {
    text-align: center;
    font-size: 20px;
    font-weight: normal;
    color: #f0faf0;
    margin-bottom: 20px; /* Abstand zwischen den Bereichen */
  }

  a:link {
    color: #f0faf0 !important; /* Waldgrün für normale Links */
    text-decoration: none; /* Entfernt die Standardunterstreichung */
  }
  
  a:visited {
  color: #f0faf0; /* Dunkles Waldgrün für besuchte Links */
  }

  a:hover {
    text-decoration: underline; /* Unterstreichung beim Hover */
  }

  .navbar {
    background-color: #4a6e4f !important;
    color: #f0faf0 !important;
  }

  .footer {
    width: 100%;
    text-align: center;
    position: fixed;
    bottom: 0;
    font-family: Georgia, serif;
    background-color: #4a6e4f !important;
    color: #f0faf0 !important;
  }

  .navbar a, .footer a {
    color: #f0faf0 !important;
  }

  .navbar a:hover, .footer a:hover {
    color: #d1e5d1 !important;
  }
  
  /* Neue Klasse für das Impressum */
  .impressum {
    margin-top: 200px; /* Abstand oben */
    font-size: 20px;
    font-weight: normal;
  }
</style>

<div class="center-text">
  <h1>Contact me</h1>
  <p><strong>E-Mail:</strong> pzerrer[at]uni-bremen.de</p>
  <p><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/patrick-zerrer-205b422a7" target="_blank">Patrick Zerrer</a></p>
  <p><strong>University Website:</strong> <a href="https://zemki.uni-bremen.de/person/patrick-zerrer/" target="_blank">Uni Bremen - ZeMKI</a></p>
</div>

<div class="impressum center-text">
  <h1>Impressum</h1>
  <p>Patrick Zerrer<br>
  Linzer Strasse 4<br>
  28359 Bremen<br>
  Deutschland</p>
  <p><strong>E-Mail:</strong> pzerrer[at]uni-bremen.de</p>
</div>

