---
page-layout: full
format: 
  html:
    link-external-newwindow: true
    css: styles.css
embed-resources: true
---

### Smartphone data 
The processing and visualisation of self-tracked smartphone data during a stay in Hamburg. A series of smartphone sensors were used for this, which were recorded using a tracking app and later processed for visualisation.


```{r, echo=FALSE, warning=FALSE}
#| column: screen-inset-shaded

# load library
library(leaflet)

# load data
load("data/pre_processed_data")

# run leaflet
leaflet() %>% 
  setView(lng = 9.970424082941788, lat =  53.553692067407596, zoom = 12) %>%
  addTiles() %>% 
  addMarkers(lng = c(gps_data_for_markers$lon),
             lat = c(gps_data_for_markers$lat),
             popup = paste0("<b>", "Location & Interval", "</b><br>", 
                            "Start of the interval: ", gps_data_for_markers$start_date_time, 
                            "<br>", "End of the interval: ", gps_data_for_markers$end_date_time,
                            "<br>", "Activity: ", gps_data_for_markers$activity_type,
                            "<br>", "Share of activity: ", gps_data_for_markers$percentage_activity,
                            "<br>", "Steps: ", gps_data_for_markers$steps,
                            "<br>", "Light: ", gps_data_for_markers$light_description,
                            "<br>", "Share of Light: ", gps_data_for_markers$percentage_light,
                            "<br>", "Weather: ", gps_data_for_markers$weather_description,
                            "<br>", "Clouds: ", gps_data_for_markers$clouds,
                            "<br>", "Temperature in Celsius: ", gps_data_for_markers$temperature,
                            "<br>", "Feels like: ", gps_data_for_markers$feels_like,
                            "<br>", "Humidity in %: ", gps_data_for_markers$humidity,
                            "<br>", "Visibility: ", gps_data_for_markers$visibility,
                            "<br>", "Wind speed in m/s: ", gps_data_for_markers$wind_speed),
                 options = markerOptions()
                 ) %>% 
      addPolylines(
        lng = c(gps_data_for_lines$lon),
        lat = c(gps_data_for_lines$lat),
        color = "darkblue",
        weight = 2,
        opacity = 0.7
      )
```

::: {.callout-tip collapse="true"}

## R-Code
```{r, eval=FALSE}
# load library
library(leaflet)

# load data
load("data/pre_processed_data")

# run leaflet
leaflet() %>% 
  # center map
  setView(lng = 9.970424082941788, lat =  53.553692067407596, zoom = 12) %>%
  # add tiles
  addTiles() %>% 
  # add descriptions
  addMarkers(lng = c(gps_data_for_markers$lon),
             lat = c(gps_data_for_markers$lat),
             popup = paste0("<b>", "Location & Interval", "</b><br>", 
                            "Start of the interval: ", gps_data_for_markers$start_date_time, 
                            "<br>", "End of the interval: ", gps_data_for_markers$end_date_time,
                            "<br>", "Activity: ", gps_data_for_markers$activity_type,
                            "<br>", "Share of activity: ", gps_data_for_markers$percentage_activity,
                            "<br>", "Steps: ", gps_data_for_markers$steps,
                            "<br>", "Light: ", gps_data_for_markers$light_description,
                            "<br>", "Share of Light: ", gps_data_for_markers$percentage_light,
                            "<br>", "Weather: ", gps_data_for_markers$weather_description,
                            "<br>", "Clouds: ", gps_data_for_markers$clouds,
                            "<br>", "Temperature in Celsius: ", gps_data_for_markers$temperature,
                            "<br>", "Feels like: ", gps_data_for_markers$feels_like,
                            "<br>", "Humidity in %: ", gps_data_for_markers$humidity,
                            "<br>", "Visibility: ", gps_data_for_markers$visibility,
                            "<br>", "Wind speed in m/s: ", gps_data_for_markers$wind_speed),
                 options = markerOptions()
                 ) %>% 
      addPolylines(
        lng = c(gps_data_for_lines$lon),
        lat = c(gps_data_for_lines$lat),
        color = "darkblue",
        weight = 2,
        opacity = 0.7
      )
```
:::

**Note:** This page is still a work in progress. I will add more data science projects in the future.

