---
title: "Population Distribution by Age" 

format:    
  html:     
    code-fold: true 
mainfont: Georgia
execute:   
  echo: false   
  warning: false

---


```{r}
library(showtext)
library(patchwork)
library(ggplot2)
library(dplyr)

font_add_google("Fraunces", "title_font")
font_add_google("Montserrat", "body_font")
showtext_auto()

body_font<- "body_font"
title_font<- "title_font"


pop<-read.csv("C:/Users/Pc/Documents/Quarto/pp/population table.csv")

df<- pop %>%
  select(Age.Groups..Years., Population, X, X.1) %>%
  filter(!row_number() %in% c(1,3)) %>%
  rename(age = Age.Groups..Years., male = X, fem = X.1, total = Population ) %>%
  filter(!row_number() %in% c(1,2)) 


df$age[df$age == '0'] <- '00 - 00'
df$age[df$age == '1'] <- '01- 1+'
df$age[df$age == '65+'] <- '65 - 65+'


## female ###

fem<-ggplot(data = df, aes(x = age, y = as.numeric(fem))) +ylab("female (%)")+
  geom_hline(yintercept = c(2,4,6,8),   color = "gray", size = 0.5)+
  geom_bar(stat = "identity", fill = "#EA498C") +
  #geom_text(aes(label = fem))+
  #geom_area()+
  
  #theme_void()+
  theme(axis.title.x = element_text(family= body_font, size=  8), 
        #axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        #axis.text.y = element_blank(), 
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#E8F6FF"),
        plot.background = element_rect(fill = "#E8F6FF"),
        legend.position = 'none',
        plot.margin = unit(c(1,0,1,1), "mm"))+coord_flip(ylim =c(0.4, 8.2))
  

### male ###

male<-ggplot(data = df , aes(x =age, y = as.numeric(male))) +
  geom_hline(yintercept = c(2,4,6,8),  color = "gray", size = 0.5)+
  geom_bar(stat = "identity", fill = "#6784AA") +
  ylab("male (%)")+
  #geom_area(color= "navyblue",outline.type = "full", alpha = 0.6)+
  #geom_text(aes(label = male))+
  
  theme(axis.title.x = element_text(family= body_font, size=  8), 
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        panel.grid = element_blank(),
        axis.ticks= element_blank(), 
        legend.position = 'none',
        panel.background = element_rect(fill = "#E8F6FF"),
        plot.background = element_rect(fill = "#E8F6FF"),
        panel.margin = unit(c(1,0,1,0), "mm"),
        plot.margin = margin(0,0,0,0),
        )+ scale_y_reverse(labels =  )+ coord_flip(ylim =c(8,0.5))


g<-male + fem +  plot_layout(ncol =2, widths = c(0.5, 0.5))

g_plus<- g + 
  labs(#title  = "Population Distribution by Age", 
       subtitle = "Age in Years",
       caption = "Vistales | Data: Pakistan Bureau of Statistics")+
  theme(
        plot.background = element_rect(fill = "#E8F6FF", colour = "#E8F6FF"),
        #plot.title = element_text(family = title_font, face = 'bold',
         #                         size = 20,color = "black", margin = margin(8, 0, 0, -180)),
        plot.subtitle = element_text(family = body_font, 
                                  size = 6.8,color = "black", margin = margin(10, 0, 5, -70)),
        plot.caption = element_text(family = body_font, face = 'bold',
                                  size = 7,color = "black", margin = margin(10, 0, 0, 0))
        )
  
showtext_opts(dpi = 320)


g_plus
#ggsave("pop.png", g_plus, dpi=320, width = 6, height = 6)




```

Pakistan ranks 5th in the world population ranking with a growth rate of 2.55%. The population pyramid depicts a nation with a significant proportion of individuals under the age of 35. 

At its core, the pyramid exhibits a pronounced width in the younger age brackets (5-24), indicative of a burgeoning youth population. 

While a youthful demographic promises economic growth, innovation, and productivity, it also presents challenges such as ensuring access to quality education, healthcare, and employment opportunities. Addressing these needs is pivotal for sustainable development. Without proper guidance and education, this youth bulge could pose significant challenges.


By investing in education, skills development, and well-being, Pakistan can leverage its demographic dividend for a brighter future.

In essence, Pakistan's population pyramid, characterized by a significant youth demographic, holds immense promise. However, realizing this potential hinges on providing quality education and opportunities for its youth, ensuring they become agents of positive change in shaping the nation's future.